Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#import library yang di butuhkan
from openpyxl import load_workbook #library untuk menampilkan dokumen
import pandas as pd #import pandas 
from nltk.tokenize import word_tokenize #import library nltk - tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory #import library sastrawi untuk

wr = load_workbook(filename = 'WrpText.xlsx')
sheet_range = wr['wrp-text']

df = pd.DataFrame(sheet_range.values)
df.columns = ['Judul', 'Waktu', 'Category', 'Isi']
df
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_14076/1496169100.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#import library yang di butuhkan[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mfrom[0m [0mopenpyxl[0m [1;32mimport[0m [0mload_workbook[0m [1;31m#library untuk menampilkan dokumen[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m [1;31m#import pandas[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0mnltk[0m[1;33m.[0m[0mtokenize[0m [1;32mimport[0m [0mword_tokenize[0m [1;31m#import library nltk - tokenize[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mSastrawi[0m[1;33m.[0m[0mStemmer[0m[1;33m.[0m[0mStemmerFactory[0m [1;32mimport[0m [0mStemmerFactory[0m [1;31m#import library sastrawi untuk[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'openpyxl'
ModuleNotFoundError: No module named 'openpyxl'

